### ISSUE TITLE
lexibankify

### ISSUE THREAD

**Issue by LinguList** [lexibank/aaleykusunda#1]
- [x] references: Aaley and Bodt
- [x] raw/wordlist (take from bodtnepal, without Tshangla etc.)
- [x] etc
- [x] NOTES.md
- [x] license
- [x] contributors.md (Mattis and Mei-Shin as maintainers, Aaley and bodt as original data collectors)

**Comment by LinguList** [comment]
you can just push, no need to make a PR first.

**Comment by Wu-Urbanek** [comment]
I am note familiar with NOTES.md, is there any example I can check?

**Comment by LinguList** [comment]
quite a few lexibannk datasets have notes.md, you can search in your
lexibank-datasets folder with `ls`:

```

$ ls lexibank-folder/*/NOTES.md

```


There are many examples. Most are just a little summary in markdown.

**Comment by Wu-Urbanek** [comment]
I will start working on the release.

**Comment by Wu-Urbanek** [comment]
Before I update to the new contributors' format, I would like to ask if the following descriptions are correct. 

Name | GitHub user | Description | Role |
--- | --- | --- | --- |
Johann-Mattis List | @LinguList| orthography profile, maintainer | Author
Mei-Shin Wu | @macyl | dataset patron, maintainer | Author
Timotheus A. Bodt| | publication author, fieldwork, orthography profile | RightsHolder, Distributor
Uday Raj Aaley| |publication author, fieldwork | RightsHolder, Distributor

**Comment by LinguList** [comment]
Yes. Since Tim provided the data in well-readable format, and also consulted us, I would assign them both the role of "Author", so they appear on the citation. And please change the order, so that we have Aaley in first row, then Bodt, then Wu, then List. And I suggest to write "patron" not dataset patron, as it is shorter.
